### ISSUE TITLE
Hierarchie an RightsStatements.org angleichen

### ISSUE THREAD

**Issue by nichtich** [dini-ag-kim/license#3]
Die Oberbegriffe sollten "Copyright" (fast alle Lizenzen, auch CC!), "No Copyright" (CC0, PDDL, WTFPL...) und "unspecified" sein (vgl. https://rightsstatements.org/). Oder soll die Gruppierung eine flache Liste bleiben?

**Comment by acka47** [comment]
Ich gebe dir Recht, dass das eine korrekte Gliederung ist, bin aber skeptisch, ob diese Hierarchie z.B. als Filter in einem Such-UI nutzer\*innenfreundlich ist. 

Du beziehst dich glaube ich u.a. auf das "Copyright" in dem jetzigen Entwurf

https://github.com/dini-ag-kim/license/blob/c0d01b061048e57dcf83d6fd65918432f113b031/license.ttl#L66-L71

Dieser Eintrag soll momentan für die Fälle stehen, in denen Urheberrecht besteht und keine Lizenz vergeben wurde, also konkret für nicht-offene urheberrechtlich geschützte Ressourcen. Dementsprechend ist es auch fraglich, ob dieser Eintrag überhaupt enthalten sein sollte, wenn es um OER geht. (Ich hatte das Vokabular zunächst von der OER World Map übernommen (https://github.com/hbz/oerworldmap/blob/master/public/json/licenses.json), um es dann nach unseren Bedürfnissen anzupassen.)
