### ISSUE TITLE
Name des Vokabulars

### ISSUE THREAD

**Issue by nichtich** [dini-ag-kim/license#4]
Der Name "Lizenzen" ist etwas zu unkonkret. Wie wäre es mit "KIM Lizenztypen" oder "OER Lizenztypen"?

**Comment by acka47** [comment]
Ich hab mal ein PR gemacht (#5). Schau mal, ob das so passt. Für den namespace finde ich `https://w3id.org/im/license/` aber ok, oder würdest du das auch lieber  `https://w3id.org/im/licensetype/` o.ä. nennen?
