### ISSUE TITLE
Ergänze eine Liste der passenden Lizenzen zu jedem Term

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/license#8]
Ich wollte gerade anfangen die Liste in OERSI als Vokabluar einzubinden, aber adhoc kann ich nicht die Lizenzen mit den Termen zusammenbringen. Vielleicht wäre es hilfreich die passenden Lizenzen im SKOS und in der SKOHUB Vocabs zu listen.

**Comment by nichtich** [comment]
Ich glaube das ist #1 oder? Ich würde eine zusätzliche RDF/Turtle-Datei anlegen. Frage ist mit welcher RDF-Property Lizenz und die Typen zusammenhängen. In anderem Kontext würde ich `rdf:type` nehmen (?).

**Comment by acka47** [comment]
> Ich glaube das ist #1 oder? 

Ja, das ist ein Duplikat. Ich mach das hier mal zu.
